name: pre-commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies
        run: poetry install

      - name: Install pre-commit
        run: poetry run pip install pre-commit

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
